version: '3'

services:
  djangostock:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/djangostock/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://stock_dev_admin:stock_dev_admin@postgres:5432/stock_dev
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - CELERY_BROKER_URL=pyamqp://rabbitmq:5672
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=stock_dev
      - POSTGRES_USER=stock_dev_admin
      - POSTGRES_PASSWORD=stock_dev_admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d stock_dev -U stock_dev_admin"]
      interval: 2s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12

  redis:
    image: redis:7.2

volumes:
  postgres_data:
