version: '3'

services:
  djangostock:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/djangostock
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://stock_dev_admin:stock_dev_admin@postgres:5432/stock_dev
    depends_on:
      postgres:
          condition: service_healthy

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=stock_dev
      - POSTGRES_USER=stock_dev_admin
      - POSTGRES_PASSWORD=stock_dev_admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d stock_dev -U stock_dev_admin"]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
