# Generated by Django 4.2.4 on 2023-08-07 11:46

from django.db import migrations

from ..serializers import CurrencySerializer, CountrySerializer

currencies = [
    {"name": "USD"},
]

countries = [
    {"name": "United States"},
]


def add_currencies(apps, schema_editor):
    for currency in currencies:
        serializer = CurrencySerializer(data=currency)
        if serializer.is_valid():
            serializer.save()


def add_countries(apps, schema_editor):
    for country in countries:
        serializer = CountrySerializer(data=country)
        if serializer.is_valid():
            serializer.save()


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0003_country_currency_stock_stocktimeseries"),
    ]

    operations = [
        migrations.RunPython(add_currencies),
        migrations.RunPython(add_countries),
    ]
