# Generated by Django 4.2.4 on 2023-08-07 11:46

from django.db import migrations


def add_currencies(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    CurrencySerializer = apps.get_model("application", "CurrencySerializer")

    CurrencySerializer(name="USD").create()


def add_countries(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    CountrySerializer = apps.get_model("application", "CountrySerializer")

    CountrySerializer(name="United States").create()


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0003_country_currency_stock_stocktimeseries"),
    ]

    operations = [
        migrations.RunPython(add_currencies),
        migrations.RunPython(add_countries),
    ]
