# Generated by Django 4.2.4 on 2023-08-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0005_alter_stock_last_update_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="last_update_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="stocktimeseries",
            name="recorded_date",
            field=models.DateField(),
        ),
    ]
